#!/usr/bin/env zsh
# This file is managed by puppet.

local lock="$1"
shift

if [[ -f "$lock" ]]; then
	exit 1
fi

function remove-lock() {
	rm -rf "$lock"
}

trap remove-lock INT TERM ERR

$@ > /dev/null 2>&1 &
echo $! > "$lock"
wait
remove-lock
