# This file is managed by puppet to allow it to hook file installation.
# Any user made changes here will be overriden. Additionally hook functionality
# will have to be provided by puppet.

if [ "${EBUILD_PHASE}" == "postinst" ]; then
	if [[ -x /etc/portage/puppet/${CATEGORY}_${PN} ]]; then 
		mkdir -p /var/log/portage
		echo "/etc/portage/puppet/${CATEGORY}_${PN}: $(date '+%s')" >> /var/log/portage/post_install.log
		/etc/portage/puppet/${CATEGORY}_${PN} >> /var/log/portage/post_install.log 2>&1
		echo >> /var/log/portage/post_install.log
	fi

	if [[ -x /etc/portage/package.post_install/${CATEGORY}/${PN} ]]; then 
		mkdir -p /var/log/portage
		echo "/etc/portage/package.post_install/${CATEGORY}/${PN}: $(date '+%s')" >> /var/log/portage/post_install.log
		/etc/portage/package.post_install/${CATEGORY}/${PN} >> /var/log/portage/post_install.log 2>&1
		echo >> /var/log/portage/post_install.log
	fi
fi
